# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# No tag as rev because they can be overwritten while sha cannot
# Check the code
# For update to the last commit `pre-commit autoupdate`. See https://pre-commit.com/#using-the-latest-version-for-a-repository
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a870 # v6.0.0
    hooks:
      - id: trailing-whitespace # trims trailing whitespace
      - id: end-of-file-fixer # makes sure files end in a newline and only a newline.
      - id: check-yaml
      - id: check-added-large-files # no commit on large files
        exclude: package-lock.json # they may be 700kb, and it's recommended to commit them in
        args: [ "--maxkb", "500" ]
      - id: detect-private-key # detect private key
        # Prevent committing inline conflict markers
      - id: check-merge-conflict
        args: [ --assume-in-merge ]
      # Checks that scripts with shebangs are executable
      - id: check-shebang-scripts-are-executable
      # Checks for symlinks which do not point to anything.
      - id: check-symlinks
  - repo: https://github.com/tcort/markdown-link-check
    rev: 3c9471f # v3.14.1
    hooks:
      - id: markdown-link-check
        name: markdown link check
        args: [ --quiet, "--config", ".config/markdown-link-check.config.json" ]
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: e46582c # v9.23.0
    hooks:
      # equivalent to:
      # commitlint --extends '@commitlint/config-conventional' --verbose --edit  "$1"
      - id: commitlint
        name: check commit message
        stages: [ commit-msg ]
        additional_dependencies: [ '@commitlint/config-conventional' ]
        args: [ "--verbose", "--config", ".config/commitlint.config.js" ]
  - repo: https://github.com/combostrap/devfiles
    rev: "v0.1.4"
    hooks:
      - id: git-prevent-out-of-sync-commit
        name: prevent out-of-sync branch commit
  - repo: https://github.com/editorconfig-checker/editorconfig-checker
    rev: c9d5ed0 # v3.4.1
    hooks:
      - id: editorconfig-checker
        args: [ "--verbose", "--config", ".config/editorconfig-checker.config.json" ]
